# -*- coding: utf-8 -*-
"""
================================================================================
V4 DCA + AI Hybrid No-Filter Backtest (定期定額 + AI 混合策略無濾網回測)
================================================================================
測試 V4 模型在兩種不同資金分配策略下的交易績效。

比較模式:
1. Strategy 1: Split 50/50 (資金對半分配)
   - 每年年初獲得額度 (External Limit) 60 萬。
   - 額度對半拆分: DCA 30 萬, AI 30 萬。
   - 資金注入 (Capital Injection): 只有在真正買入時，才從額度轉入帳戶。
     - DCA: 每月從額度轉入 2.5 萬 (30萬/12) 買股。
     - AI: 只有發出買訊時，從 AI 額度轉入資金 (100% All-in) 買股。
   - 帳戶結構: Portfolio Value = 持股現值 + 內部現金 (Selected Sales)。
   - 額度 (External Limit) 不計入 Portfolio Value，直到注入。

2. Strategy 2: Shared Pool (資金池共享)
   - 每年年初獲得 60 萬額度。
   - DCA 與 AI 共享此額度。
   - 定期定額 (DCA): 每月 5 萬元 (優先使用內部現金)。
   - AI 自由操作: 當有額度或內部現金時，每次買入 5 萬元。
   - 資金循環: AI 賣出後資金回流至內部現金 (Internal Cash)，可供 DCA 或 AI 再次使用 (Releasing Quota)。
   - 沒錢時 (額度用完且無內部現金) 暫停買入。

比較基準 (Benchmarks):
1. 純定期定額：每月 5 萬元 (Pure DCA)
2. 年初一次投入：每年 60 萬 Buy & Hold (Yearly Lump Sum)

作者：Phil Liang (Generated by Gemini)
日期：2025-12-13 (Updated)
================================================================================
"""

import os
import sys
import pickle
import argparse
from datetime import datetime

# Windows UTF-8 設定
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from stable_baselines3 import PPO

# 中文字型設定
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

# =============================================================================
# 設定
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
V4_MODELS_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v4')
RESULTS_PATH = os.path.join(PROJECT_PATH, 'results_backtest_v4_dca_hybrid_no_filter')
CACHE_DIR = os.path.join(PROJECT_PATH, 'data', 'processed')

DEFAULT_START_DATE = '2023-01-01'  
DEFAULT_END_DATE = None
YEARLY_CAPITAL = 600_000  
MONTHLY_DCA_BENCHMARK = 50_000  


def parse_args():
    parser = argparse.ArgumentParser(
        description='V4 DCA + AI Hybrid No-Filter Backtest',
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument('--start', type=str, default=DEFAULT_START_DATE)
    parser.add_argument('--end', type=str, default=DEFAULT_END_DATE)
    return parser.parse_args()


def load_lstm_models_for_backtest(cutoff_date):
    import ptrl_hybrid_system as hybrid
    import twii_model_registry_multivariate as lstm_1d_module
    import twii_model_registry_5d as lstm_5d_module
    import twii_model_registry_20d as lstm_20d_module  # [v4.0] 新增 T+20
    
    print(f"\n[LSTM] Loading models with cutoff_date: {cutoff_date}")
    meta_1d = lstm_1d_module.select_best_model(cutoff_date)
    if meta_1d is None: return False
    
    model_1d, scaler_feat_1d, scaler_tgt_1d, _ = lstm_1d_module.load_artifacts(meta_1d['train_start'], meta_1d['train_end'])
    print(f"  ✅ T+1 Model: {meta_1d['train_start']} ~ {meta_1d['train_end']}")
    
    meta_5d = lstm_5d_module.select_best_model(cutoff_date)
    if meta_5d is None: return False
    
    model_5d, scaler_feat_5d, scaler_tgt_5d, _ = lstm_5d_module.load_artifacts(meta_5d['train_start'], meta_5d['train_end'])
    print(f"  ✅ T+5 Model: {meta_5d['train_start']} ~ {meta_5d['train_end']}")
    
    # [v4.0] 新增 T+20 模型載入
    meta_20d = lstm_20d_module.select_best_model(cutoff_date)
    if meta_20d is None: return False
    
    model_20d, scaler_feat_20d, scaler_tgt_20d, _ = lstm_20d_module.load_artifacts(meta_20d['train_start'], meta_20d['train_end'])
    print(f"  ✅ T+20 Model: {meta_20d['train_start']} ~ {meta_20d['train_end']}")
    
    # 注入到 hybrid 模組 (含 T+20)
    hybrid._LSTM_MODELS.update({
        'model_1d': model_1d, 'scaler_feat_1d': scaler_feat_1d, 'scaler_tgt_1d': scaler_tgt_1d, 'meta_1d': meta_1d,
        'model_5d': model_5d, 'scaler_feat_5d': scaler_feat_5d, 'scaler_tgt_5d': scaler_tgt_5d, 'meta_5d': meta_5d,
        'model_20d': model_20d, 'scaler_feat_20d': scaler_feat_20d, 'scaler_tgt_20d': scaler_tgt_20d, 'meta_20d': meta_20d,
        'loaded': True
    })
    return True


# =============================================================================
# Strategy 1: Split 50/50 (Injection Mode)
# =============================================================================
class DCAHybridBacktester:
    def __init__(self, buy_model, sell_model, yearly_capital=600_000):
        self.buy_model = buy_model
        self.sell_model = sell_model
        self.yearly_capital = yearly_capital
        
        self.trades = []
        self.equity_curve = []
        self.dca_buy_signals = []      
        self.ai_buy_signals = []       
        self.ai_sell_signals = []      
        self.daily_confidence = []     
        self.total_invested = 0
    
    def run(self, df: pd.DataFrame, feature_cols: list) -> dict:
        features = df[feature_cols].values.astype(np.float32)
        close_prices = df['Close'].values
        dates = df.index
        
        dca_limit = 0       
        ai_limit = 0        
        dca_shares = 0      
        dca_internal_cash = 0  
        ai_internal_cash = 0   
        ai_position = None     
        
        current_year = None
        last_dca_month = None
        
        print(f"[Strategy 1] Period: {dates[0].strftime('%Y-%m-%d')} ~ {dates[-1].strftime('%Y-%m-%d')}")
        print(f"[Strategy 1] Yearly Limit: ${self.yearly_capital:,.0f} (Split 50/50)")
        
        for i in range(len(df)):
            date = dates[i]
            price = close_prices[i]
            year = date.year
            month = date.month
            
            if current_year != year:
                current_year = year
                last_dca_month = None
                dca_limit += self.yearly_capital / 2
                ai_limit += self.yearly_capital / 2
                print(f"  [{year}] New Year +${self.yearly_capital:,.0f}. DCA Lim: {dca_limit:,.0f}, AI Lim: {ai_limit:,.0f}")

            # DCA (Monthly)
            if last_dca_month != month:
                last_dca_month = month
                target_amt = 25_000 # Fixed 300k / 12
                needed = target_amt - dca_internal_cash
                
                if needed > 0:
                    inj_amount = min(needed, dca_limit)
                    dca_limit -= inj_amount
                    dca_internal_cash += inj_amount
                    self.total_invested += inj_amount
                
                if dca_internal_cash >= price:
                    shares = int(dca_internal_cash / price)
                    cost = shares * price
                    dca_internal_cash -= cost
                    dca_shares += shares
                    self.dca_buy_signals.append((date, price, shares))
            
            # AI
            obs = np.nan_to_num(features[i], nan=0.0, posinf=1.0, neginf=-1.0)
            
            if ai_position is not None:
                current_return = price / ai_position['buy_price']
                hold_days = i - ai_position['buy_idx']
                sell_obs = np.concatenate([obs, [current_return]]).astype(np.float32).reshape(1, -1)
                action, _ = self.sell_model.predict(sell_obs, deterministic=True)
                sell_probs = self.sell_model.policy.get_distribution(self.sell_model.policy.obs_to_tensor(sell_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
                sell_conf = float(sell_probs[1]) if action[0] == 1 else float(sell_probs[0])
                
                log_entry = {'date': date, 'status': 'holding', 'price': price, 'sell_conf': sell_conf, 'buy_conf': 0, 'action': 'hold'}
                self.daily_confidence.append(log_entry)
                
                if action[0] == 1 or current_return < 0.92:
                    log_entry['action'] = 'SELL'
                    proceeds = ai_position['shares'] * price
                    profit = proceeds - ai_position['cost']
                    ai_internal_cash += proceeds
                    self.trades.append({'type': 'AI', 'return': current_return - 1, 'profit': profit, 'hold_days': hold_days})
                    self.ai_sell_signals.append({'date': date, 'price': price, 'confidence': sell_conf})
                    ai_position = None
            
            elif ai_position is None:
                available_fund = ai_internal_cash + ai_limit
                buy_conf = 0
                if available_fund >= price:
                    buy_obs = obs.reshape(1, -1)
                    action, _ = self.buy_model.predict(buy_obs, deterministic=True)
                    buy_probs = self.buy_model.policy.get_distribution(self.buy_model.policy.obs_to_tensor(buy_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
                    buy_conf = float(buy_probs[1]) if action[0] == 1 else float(buy_probs[0])
                    
                    log_entry = {'date': date, 'status': 'idle_check_buy', 'price': price, 'buy_conf': buy_conf, 'sell_conf': 0, 'action': 'wait'}
                    self.daily_confidence.append(log_entry)

                    if action[0] == 1:
                        # 100% Invest
                        invest_amt = available_fund
                        used_internal = min(ai_internal_cash, invest_amt)
                        needed_external = invest_amt - used_internal
                        
                        if ai_limit >= needed_external:
                            log_entry['action'] = 'BUY'
                            ai_limit -= needed_external
                            ai_internal_cash += needed_external
                            self.total_invested += needed_external
                            
                            shares = int(invest_amt / price)
                            cost = shares * price
                            ai_internal_cash -= cost
                            ai_position = {'shares': shares, 'buy_price': price, 'buy_idx': i, 'cost': cost}
                            self.ai_buy_signals.append({'date': date, 'price': price, 'confidence': buy_conf})

            # Value = Assets + Internal Cash
            total_val = (dca_shares * price + dca_internal_cash) + \
                        ((ai_position['shares'] * price if ai_position else 0) + ai_internal_cash)
            
            self.equity_curve.append({'date': date, 'value': total_val})
            
        return self._calculate_metrics()

    def _calculate_metrics(self) -> dict:
        if not self.equity_curve: return {}
        equity_df = pd.DataFrame(self.equity_curve).set_index('date')
        final = equity_df['value'].iloc[-1]
        total_return = (final - self.total_invested) / self.total_invested if self.total_invested > 0 else 0
        days = (equity_df.index[-1] - equity_df.index[0]).days
        annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
        
        daily_ret = equity_df['value'].pct_change().fillna(0)
        sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
        
        roll_max = equity_df['value'].cummax()
        max_dd = ((equity_df['value'] - roll_max) / roll_max).min()
        
        wins = sum(1 for t in self.trades if t['return'] > 0)
        win_rate = wins / len(self.trades) if self.trades else 0
        
        return {
            'total_invested': self.total_invested,
            'final_value': final,
            'total_return': total_return,
            'annualized_return': annualized,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_dd,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'equity_df': equity_df,
            'dca_buys': len(self.dca_buy_signals),
            'ai_buys': len(self.ai_buy_signals)
        }


# =============================================================================
# Strategy 2: Shared Pool (Injection Mode)
# =============================================================================
class SharedPoolBacktester:
    def __init__(self, buy_model, sell_model, yearly_capital=600_000, 
                 dca_amount=50_000, ai_chunk_amount=50_000):
        self.buy_model = buy_model
        self.sell_model = sell_model
        self.yearly_capital = yearly_capital
        self.dca_amount = dca_amount
        self.ai_chunk_amount = ai_chunk_amount
        
        self.trades = []
        self.equity_curve = []
        self.dca_buy_signals = []      
        self.ai_buy_signals = []       
        self.ai_sell_signals = []      
        self.daily_confidence = []
        self.total_invested = 0

    def run(self, df: pd.DataFrame, feature_cols: list) -> dict:
        features = df[feature_cols].values.astype(np.float32)
        close_prices = df['Close'].values
        dates = df.index
        
        external_limit = 0     
        internal_cash = 0      
        dca_shares = 0
        ai_positions = []      
        
        current_year = None
        last_dca_month = None
        
        print(f"[Strategy 2] Period: {dates[0].strftime('%Y-%m-%d')} ~ {dates[-1].strftime('%Y-%m-%d')}")
        print(f"[Strategy 2] Shared Limit: Yearly +${self.yearly_capital:,.0f}")
        
        for i in range(len(df)):
            date = dates[i]
            price = close_prices[i]
            year = date.year
            month = date.month
            
            if current_year != year:
                current_year = year
                last_dca_month = None
                external_limit += self.yearly_capital
                print(f"  [{year}] +${self.yearly_capital:,.0f} Lim. Avail Ext: {external_limit:,.0f}, Int Cash: {internal_cash:,.0f}")

            def try_allocate_funds(amount):
                nonlocal internal_cash, external_limit
                allocated = 0
                if internal_cash >= amount:
                    internal_cash -= amount
                    allocated = amount
                else:
                    use_int = internal_cash
                    needed = amount - use_int
                    if external_limit >= needed:
                        internal_cash = 0
                        external_limit -= needed
                        self.total_invested += needed 
                        allocated = amount
                return allocated

            # DCA (Monthly)
            if last_dca_month != month:
                last_dca_month = month
                fund = try_allocate_funds(self.dca_amount)
                if fund > 0:
                    shares = int(fund / price)
                    cost = shares * price
                    internal_cash += (fund - cost)
                    dca_shares += shares
                    self.dca_buy_signals.append((date, price, shares))
            
            # AI
            obs = np.nan_to_num(features[i], nan=0.0, posinf=1.0, neginf=-1.0)
            
            for idx in range(len(ai_positions) - 1, -1, -1):
                pos = ai_positions[idx]
                hold_days = i - pos['buy_idx']
                current_return = price / pos['buy_price']
                sell_obs = np.concatenate([obs, [current_return]]).astype(np.float32).reshape(1, -1)
                action, _ = self.sell_model.predict(sell_obs, deterministic=True)
                
                sell_probs = self.sell_model.policy.get_distribution(self.sell_model.policy.obs_to_tensor(sell_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
                sell_conf = float(sell_probs[1]) if action[0] == 1 else float(sell_probs[0])
                
                log_entry = {'date': date, 'status': 'holding', 'price': price, 'sell_conf': sell_conf, 'buy_conf': 0, 'action': 'hold'}
                self.daily_confidence.append(log_entry)
                
                if action[0] == 1 or current_return < 0.92:
                    log_entry['action'] = 'SELL'
                    proceeds = pos['shares'] * price
                    profit = proceeds - pos['cost']
                    internal_cash += proceeds 
                    self.trades.append({'type': 'AI_S2', 'return': current_return - 1, 'profit': profit, 'hold_days': hold_days})
                    self.ai_sell_signals.append({'date': date, 'price': price, 'confidence': sell_conf})
                    ai_positions.pop(idx)

            if (internal_cash + external_limit) >= self.ai_chunk_amount:
                buy_obs = obs.reshape(1, -1)
                action, _ = self.buy_model.predict(buy_obs, deterministic=True)
                buy_probs = self.buy_model.policy.get_distribution(self.buy_model.policy.obs_to_tensor(buy_obs)[0]).distribution.probs.detach().cpu().numpy()[0]
                buy_conf = float(buy_probs[1]) if action[0] == 1 else float(buy_probs[0])
                
                log_entry = {'date': date, 'status': 'check_buy', 'price': price, 'buy_conf': buy_conf, 'action': 'wait'}
                self.daily_confidence.append(log_entry)

                if action[0] == 1:
                    fund = try_allocate_funds(self.ai_chunk_amount)
                    if fund > 0:
                        log_entry['action'] = 'BUY'
                        shares = int(fund / price)
                        cost = shares * price
                        internal_cash += (fund - cost)
                        ai_positions.append({'shares': shares, 'buy_price': price, 'buy_idx': i, 'cost': cost})
                        self.ai_buy_signals.append({'date': date, 'price': price, 'confidence': buy_conf})

            # Value = Stock + Internal Cash
            dca_val = dca_shares * price
            ai_val = sum(p['shares'] * price for p in ai_positions)
            total_val = dca_val + ai_val + internal_cash
            
            self.equity_curve.append({'date': date, 'value': total_val})
            
        return self._calculate_metrics()

    def _calculate_metrics(self) -> dict:
        if not self.equity_curve: return {}
        equity_df = pd.DataFrame(self.equity_curve).set_index('date')
        final = equity_df['value'].iloc[-1]
        total_return = (final - self.total_invested) / self.total_invested if self.total_invested > 0 else 0
        days = (equity_df.index[-1] - equity_df.index[0]).days
        annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
        daily_ret = equity_df['value'].pct_change().fillna(0)
        sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
        roll_max = equity_df['value'].cummax()
        max_dd = ((equity_df['value'] - roll_max) / roll_max).min()
        
        wins = sum(1 for t in self.trades if t['return'] > 0)
        win_rate = wins / len(self.trades) if self.trades else 0
        return {
            'total_invested': self.total_invested,
            'final_value': final,
            'total_return': total_return,
            'annualized_return': annualized,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_dd,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'equity_df': equity_df,
            'dca_buys': len(self.dca_buy_signals),
            'ai_buys': len(self.ai_buy_signals)
        }


def calculate_pure_dca(df: pd.DataFrame, monthly_amount: float = 50_000):
    close_prices = df['Close'].values
    dates = df.index
    shares = 0
    total_invested = 0
    equity_curve = []
    last_month = None
    
    for i in range(len(df)):
        date = dates[i]
        price = close_prices[i]
        year = date.year
        month = date.month
        if last_month != month:
            last_month = month
            shares_to_buy = int(monthly_amount / price)
            if shares_to_buy > 0:
                shares += shares_to_buy
                total_invested += shares_to_buy * price
        equity_curve.append({'date': date, 'value': shares * price})
    
    equity_df = pd.DataFrame(equity_curve).set_index('date')
    final = equity_df['value'].iloc[-1]
    total_return = (final - total_invested) / total_invested if total_invested > 0 else 0
    
    days = (equity_df.index[-1] - equity_df.index[0]).days
    annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
    daily_ret = equity_df['value'].pct_change().fillna(0)
    sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
    max_dd = ((equity_df['value'] - equity_df['value'].cummax()) / equity_df['value'].cummax()).min()
    
    return {
        'total_invested': total_invested, 'final_value': final, 'total_return': total_return,
        'annualized_return': annualized, 'sharpe_ratio': sharpe, 'max_drawdown': max_dd, 'equity_df': equity_df
    }


def calculate_yearly_lumpsum(df: pd.DataFrame, yearly_amount: float = 600_000):
    close_prices = df['Close'].values
    dates = df.index
    shares = 0
    total_invested = 0
    equity_curve = []
    current_year = None
    
    for i in range(len(df)):
        date = dates[i]
        price = close_prices[i]
        year = date.year
        if current_year != year:
            current_year = year
            shares_to_buy = int(yearly_amount / price)
            if shares_to_buy > 0:
                shares += shares_to_buy
                total_invested += shares_to_buy * price
        equity_curve.append({'date': date, 'value': shares * price})
    
    equity_df = pd.DataFrame(equity_curve).set_index('date')
    final = equity_df['value'].iloc[-1]
    total_return = (final - total_invested) / total_invested if total_invested > 0 else 0
    days = (equity_df.index[-1] - equity_df.index[0]).days
    annualized = (1 + total_return) ** (365/days) - 1 if days > 0 else 0
    daily_ret = equity_df['value'].pct_change().fillna(0)
    sharpe = (daily_ret.mean() * 252) / (daily_ret.std() * np.sqrt(252)) if daily_ret.std() > 0 else 0
    max_dd = ((equity_df['value'] - equity_df['value'].cummax()) / equity_df['value'].cummax()).min()
    
    return {
        'total_invested': total_invested, 'final_value': final, 'total_return': total_return,
        'annualized_return': annualized, 'sharpe_ratio': sharpe, 'max_drawdown': max_dd, 'equity_df': equity_df
    }


def main():
    args = parse_args()
    start_date = pd.Timestamp(args.start)
    end_date = pd.Timestamp(args.end) if args.end else None
    
    print("=" * 70)
    print("V4 DCA + AI Hybrid No-Filter Backtest (Injection Mode)")
    print("=" * 70)
    print(f"  Start: {start_date}")
    
    os.makedirs(RESULTS_PATH, exist_ok=True)
    
    print("\n[Model] Loading V4 models...")
    buy_model = PPO.load(os.path.join(V4_MODELS_PATH, 'ppo_buy_twii_final.zip'))
    sell_model = PPO.load(os.path.join(V4_MODELS_PATH, 'ppo_sell_twii_final.zip'))
    
    print("\n[Data] Loading data...")
    import ptrl_hybrid_system as hybrid
    load_lstm_models_for_backtest(start_date.date())
    
    # [v4.0] 強制重新計算特徵，確保 LSTM 預測與載入的模型一致
    print("  [Compute] Load ^TWII from local CSV (always recalculate)...")
    twii_raw = hybrid._load_local_twii_data(start_date="2000-01-01")
    twii_full_df = hybrid.calculate_features(twii_raw, twii_raw, ticker="^TWII", use_cache=False)
    
    twii_backtest_df = twii_full_df[twii_full_df.index >= start_date]
    if end_date: twii_backtest_df = twii_backtest_df[twii_backtest_df.index <= end_date]
    
    print("\n[Backtest] Running Strategy 1: Split 50/50...")
    bt1 = DCAHybridBacktester(buy_model, sell_model, YEARLY_CAPITAL)
    m1 = bt1.run(twii_backtest_df, hybrid.FEATURE_COLS)

    print("\n[Backtest] Running Strategy 2: Shared Pool...")
    bt2 = SharedPoolBacktester(buy_model, sell_model, YEARLY_CAPITAL)
    m2 = bt2.run(twii_backtest_df, hybrid.FEATURE_COLS)
    
    print("\n[Benchmark] Calculating benchmarks...")
    dca_bench = calculate_pure_dca(twii_backtest_df, MONTHLY_DCA_BENCHMARK)
    lump_bench = calculate_yearly_lumpsum(twii_backtest_df, YEARLY_CAPITAL)
    
    print("\n" + "=" * 110)
    print("Performance Comparison: Strat 1 (Split) vs Strat 2 (Shared) vs Benchmarks")
    print("=" * 110)
    print(f"{'Metric':<20} {'Strat 1 (Split)':>20} {'Strat 2 (Shared)':>20} {'Pure DCA (50k)':>20} {'Yearly Lump Sum':>20}")
    print("-" * 110)
    print(f"{'Total Invested':<20} ${m1['total_invested']:>18,.0f} ${m2['total_invested']:>18,.0f} ${dca_bench['total_invested']:>18,.0f} ${lump_bench['total_invested']:>18,.0f}")
    print(f"{'Final Value':<20} ${m1['final_value']:>18,.0f} ${m2['final_value']:>18,.0f} ${dca_bench['final_value']:>18,.0f} ${lump_bench['final_value']:>18,.0f}")
    print(f"{'Total Return':<20} {m1['total_return']*100:>19.2f}% {m2['total_return']*100:>19.2f}% {dca_bench['total_return']*100:>19.2f}% {lump_bench['total_return']*100:>19.2f}%")
    print(f"{'Annualized Return':<20} {m1['annualized_return']*100:>19.2f}% {m2['annualized_return']*100:>19.2f}% {dca_bench['annualized_return']*100:>19.2f}% {lump_bench['annualized_return']*100:>19.2f}%")
    print(f"{'Sharpe Ratio':<20} {m1['sharpe_ratio']:>20.2f} {m2['sharpe_ratio']:>20.2f} {dca_bench['sharpe_ratio']:>20.2f} {lump_bench['sharpe_ratio']:>20.2f}")
    print(f"{'Max Drawdown':<20} {m1['max_drawdown']*100:>19.2f}% {m2['max_drawdown']*100:>19.2f}% {dca_bench['max_drawdown']*100:>19.2f}% {lump_bench['max_drawdown']*100:>19.2f}%")
    print("-" * 110)
    print(f"{'DCA Buys':<20} {m1['dca_buys']:>20} {m2['dca_buys']:>20}")
    print(f"{'AI Trades':<20} {m1['total_trades']:>20} {m2['total_trades']:>20}")
    print(f"{'AI Win Rate':<20} {m1['win_rate']*100:>19.1f}% {m2['win_rate']*100:>19.1f}%")
    print("=" * 110)
    
    # Charts (Updated: 3 Subplots)
    fig, axes = plt.subplots(3, 1, figsize=(16, 18))
    
    # 1. Equity
    ax1 = axes[0]
    ax1.plot(m1['equity_df'].index, m1['equity_df']['value'], label='Strat 1 (Split)', color='blue', linewidth=2)
    ax1.plot(m2['equity_df'].index, m2['equity_df']['value'], label='Strat 2 (Shared)', color='purple', linewidth=2) 
    ax1.plot(dca_bench['equity_df'].index, dca_bench['equity_df']['value'], label='Pure DCA', color='orange', linewidth=1.5, linestyle='--')
    ax1.plot(lump_bench['equity_df'].index, lump_bench['equity_df']['value'], label='Yearly Lump', color='gray', linewidth=1.5, alpha=0.7)
    date_range_str = f"{twii_backtest_df.index[0].strftime('%Y-%m-%d')} ~ {twii_backtest_df.index[-1].strftime('%Y-%m-%d')}"
    ax1.set_title(f'V4 DCA+AI Hybrid Strategies Comparison ({date_range_str})', fontsize=14)
    ax1.set_ylabel('Portfolio Value ($)')
    ax1.legend(loc='upper left')
    ax1.grid(True, alpha=0.3)
    
    price_slice = twii_backtest_df['Close']
    
    # 2. Strat 1 Signals
    ax2 = axes[1]
    ax2.plot(price_slice.index, price_slice.values, label='^TWII', color='black', linewidth=1)
    if bt1.dca_buy_signals:
        dca_dates, dca_prices, _ = zip(*bt1.dca_buy_signals)
        ax2.scatter(dca_dates, dca_prices, marker='o', color='cyan', s=30, label='S1: DCA Buy', alpha=0.6)
    if bt1.ai_buy_signals:
        ai_buy_dates = [s['date'] for s in bt1.ai_buy_signals]
        ai_buy_prices = [s['price'] for s in bt1.ai_buy_signals]
        ax2.scatter(ai_buy_dates, ai_buy_prices, marker='^', color='blue', s=80, label='S1: AI Buy')
    if bt1.ai_sell_signals:
        ai_sell_dates = [s['date'] for s in bt1.ai_sell_signals]
        ai_sell_prices = [s['price'] for s in bt1.ai_sell_signals]
        ax2.scatter(ai_sell_dates, ai_sell_prices, marker='v', color='red', s=80, label='S1: AI Sell')
    ax2.set_title('Strategy 1 (Split 50/50) Trade Signals', fontsize=14)
    ax2.set_ylabel('Price')
    ax2.legend(loc='upper left')
    ax2.grid(True, alpha=0.3)
    
    # 3. Strat 2 Signals
    ax3 = axes[2]
    ax3.plot(price_slice.index, price_slice.values, label='^TWII', color='black', linewidth=1)
    if bt2.dca_buy_signals:
        dca_dates, dca_prices, _ = zip(*bt2.dca_buy_signals)
        ax3.scatter(dca_dates, dca_prices, marker='o', color='orange', s=30, label='S2: DCA Buy', alpha=0.6)
    if bt2.ai_buy_signals:
        ai_buy_dates = [s['date'] for s in bt2.ai_buy_signals]
        ai_buy_prices = [s['price'] for s in bt2.ai_buy_signals]
        ax3.scatter(ai_buy_dates, ai_buy_prices, marker='^', color='purple', s=80, label='S2: AI Buy')
    if bt2.ai_sell_signals:
        ai_sell_dates = [s['date'] for s in bt2.ai_sell_signals]
        ai_sell_prices = [s['price'] for s in bt2.ai_sell_signals]
        ax3.scatter(ai_sell_dates, ai_sell_prices, marker='v', color='green', s=80, label='S2: AI Sell')
    ax3.set_title('Strategy 2 (Shared Pool) Trade Signals', fontsize=14)
    ax3.set_ylabel('Price')
    ax3.legend(loc='upper left')
    ax3.grid(True, alpha=0.3)
    
    plt.tight_layout()
    start_str = twii_backtest_df.index[0].strftime('%Y%m%d')
    end_str = twii_backtest_df.index[-1].strftime('%Y%m%d')
    save_path = os.path.join(RESULTS_PATH, f'backtest_comparison_{start_str}_{end_str}.png')
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"\n[Output] Chart: {save_path}")
    plt.close()
    
    metrics_df = pd.DataFrame({
        'Metric': ['Total_Invested', 'Final_Value', 'Total_Return_Pct', 'Annualized_Return_Pct', 'Sharpe_Ratio', 'Max_Drawdown_Pct', 'DCA_Buys', 'AI_Trades', 'AI_Win_Rate_Pct'],
        'Strat1_Split': [m1['total_invested'], m1['final_value'], m1['total_return']*100, m1['annualized_return']*100, m1['sharpe_ratio'], m1['max_drawdown']*100, m1['dca_buys'], m1['total_trades'], m1['win_rate']*100],
        'Strat2_Shared': [m2['total_invested'], m2['final_value'], m2['total_return']*100, m2['annualized_return']*100, m2['sharpe_ratio'], m2['max_drawdown']*100, m2['dca_buys'], m2['total_trades'], m2['win_rate']*100],
        'Pure_DCA': [dca_bench['total_invested'], dca_bench['final_value'], dca_bench['total_return']*100, dca_bench['annualized_return']*100, dca_bench['sharpe_ratio'], dca_bench['max_drawdown']*100, 'N/A', 'N/A', 'N/A'],
        'Yearly_Lump': [lump_bench['total_invested'], lump_bench['final_value'], lump_bench['total_return']*100, lump_bench['annualized_return']*100, lump_bench['sharpe_ratio'], lump_bench['max_drawdown']*100, 'N/A', 'N/A', 'N/A']
    })
    metrics_path = os.path.join(RESULTS_PATH, f'metrics_comparison_{start_str}_{end_str}.csv')
    metrics_df.to_csv(metrics_path, index=False, encoding='utf-8-sig')
    print(f"[Output] Metrics: {metrics_path}")
    
    if bt2.trades:
        trades_df = pd.DataFrame(bt2.trades)
        trades_path = os.path.join(RESULTS_PATH, f'trades_strat2_{start_str}_{end_str}.csv')
        trades_df.to_csv(trades_path, index=False)
        print(f"[Output] Strat 2 Trades: {trades_path}")

    # New Exports
    if bt1.trades:
        trades1_df = pd.DataFrame(bt1.trades)
        trades1_path = os.path.join(RESULTS_PATH, f'trades_strat1_{start_str}_{end_str}.csv')
        trades1_df.to_csv(trades1_path, index=False)
        print(f"[Output] Strat 1 Trades: {trades1_path}")

    if bt1.daily_confidence:
        conf1_df = pd.DataFrame(bt1.daily_confidence)
        conf1_path = os.path.join(RESULTS_PATH, f'daily_confidence_strat1_{start_str}_{end_str}.csv')
        conf1_df.to_csv(conf1_path, index=False)
        print(f"[Output] Strat 1 Daily Confidence: {conf1_path}")

    if bt2.daily_confidence:
        conf2_df = pd.DataFrame(bt2.daily_confidence)
        conf2_path = os.path.join(RESULTS_PATH, f'daily_confidence_strat2_{start_str}_{end_str}.csv')
        conf2_df.to_csv(conf2_path, index=False)
        print(f"[Output] Strat 2 Daily Confidence: {conf2_path}")


if __name__ == "__main__":
    main()
