# -*- coding: utf-8 -*-
"""
================================================================================
Daily Operations V5 - Fixed LSTM 盤後分析 (No Filter Mode)
================================================================================
盤後執行腳本 - 使用 V5 模型 (對稱獎勵訓練) + 固定 LSTM 模型

**V5 模型特點**:
- Buy Agent 使用對稱獎勵結構訓練
- 無 Donchian 濾網限制，AI 可自由判斷買入時機
- Sell Agent 與 V4 相同

**Fixed LSTM 特點**:
- 不進行每日重訓，結果完全可重現
- 讀取 backtest_v5_dca_hybrid_no_filter_fixed_lstm.py 產生的 lstm_info.json
- 使用與回測相同的 LSTM 模型 (T+20, T+5, T+1)
- 使用盤後完整資料 (非盤中估計值)

流程:
1. 讀取回測產生的 lstm_info.json 取得 Fixed LSTM 路徑
2. 載入 Fixed LSTM 模型
3. 讀取本地 CSV 的完整盤後資料
4. 使用 Fixed LSTM 進行特徵工程與預測
5. 輸出結果到 daily_runs_v5_fixed/{date}/

作者：Phil Liang (Generated by Gemini)
日期：2025-12-27
================================================================================
"""

import os
import sys
import glob
import json
import pickle
import subprocess
import shutil
import re
from datetime import datetime, timedelta

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
from tensorflow import keras

# =============================================================================
# 引用主系統
# =============================================================================
import ptrl_hybrid_system as core_system

# =============================================================================
# 設定路徑
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
DAILY_RUNS_PATH = os.path.join(PROJECT_PATH, 'daily_runs_v5_fixed')  # V5 Fixed LSTM 專用資料夾
CSV_FILE = os.path.join(PROJECT_PATH, 'twii_data_from_2000_01_01.csv')

# RL 模型路徑 (V5)
V5_MODEL_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v5')

# 回測結果路徑 (用於讀取持倉狀態和 LSTM 資訊)
BACKTEST_RESULTS_PATH = os.path.join(PROJECT_PATH, 'results_backtest_v5_dca_hybrid_no_filter_fixed_lstm')


# =============================================================================
# 輔助函式: 互動式 CSV 選單
# =============================================================================
def interactive_select_csv(csv_files: list, default_index: int = -1) -> str:
    """
    使用方向鍵選擇 CSV 檔案
    """
    import msvcrt
    
    if default_index < 0:
        default_index = len(csv_files) + default_index
    
    current = default_index
    
    def render_menu():
        print("\033[H\033[J", end="")  # Clear screen
        print("📂 請選擇回測 CSV (↑↓ 選擇, Enter 確認):")
        print("-" * 50)
        for i, f in enumerate(csv_files):
            marker = "  ▶ " if i == current else "    "
            suffix = " ◀" if i == current else ""
            print(f"{marker}{os.path.basename(f)}{suffix}")
        print("-" * 50)
    
    while True:
        render_menu()
        key = msvcrt.getch()
        
        if key == b'\xe0':  # Arrow key prefix
            key2 = msvcrt.getch()
            if key2 == b'H':  # Up
                current = (current - 1) % len(csv_files)
            elif key2 == b'P':  # Down
                current = (current + 1) % len(csv_files)
        elif key == b'\r':  # Enter
            print(f"\n✅ 已選擇: {os.path.basename(csv_files[current])}")
            return csv_files[current]


# =============================================================================
# 輔助函式: 讀取回測結果
# =============================================================================
def load_latest_backtest_status(backtest_start: str = None, interactive: bool = False) -> dict:
    """
    讀取回測 daily_action_strat1 CSV (Strategy 1: Leverage Mode)，取得持倉狀態與槓桿資訊
    """
    pattern = os.path.join(BACKTEST_RESULTS_PATH, 'daily_action_strat1_*.csv')
    csv_files = sorted(glob.glob(pattern))
    
    if not csv_files:
        print(f"[Warning] 找不到回測結果: {pattern}")
        return {'found': False}
    
    # 互動選擇或自動選擇
    if interactive and len(csv_files) > 1:
        selected_csv = interactive_select_csv(csv_files)
    elif backtest_start:
        start_normalized = backtest_start.replace('-', '')
        matched = [f for f in csv_files if start_normalized in os.path.basename(f)]
        selected_csv = matched[0] if matched else csv_files[-1]
    else:
        selected_csv = csv_files[-1]
    
    print(f"[Backtest] 讀取: {os.path.basename(selected_csv)}")
    
    df = pd.read_csv(selected_csv)
    last_row = df.iloc[-1]
    
    # 計算目前的 Peak Price (依照 Strategy 1 邏輯)
    # 邏輯: 非槓桿模式時，更新最高價；槓桿模式時，最高價鎖定 (作為出場基準)
    current_peak_price = 0
    for _, row in df.iterrows():
        # 如果 CSV 中有 leveraged_mode 欄位
        if 'leveraged_mode' in row:
            is_leveraged = bool(row['leveraged_mode'])
            price = float(row['price'])
            if not is_leveraged:
                if price > current_peak_price:
                    current_peak_price = price
        else:
            # 舊版 CSV 相容
            current_peak_price = max(current_peak_price, float(row['price']))

    # 讀取 open_positions
    open_pos_file = selected_csv.replace('daily_action_strat1_', 'open_positions_strat1_')
    open_positions = []
    if os.path.exists(open_pos_file):
        pos_df = pd.read_csv(open_pos_file)
        for _, row in pos_df.iterrows():
            open_positions.append({
                'buy_date': row['buy_date'],
                'buy_price': row['buy_price'],
                'shares': row.get('shares', 1),
                'cost': row.get('cost', row['buy_price'])
            })
        print(f"  AI 持倉: {len(open_positions)} 筆")
    
    # 取得槓桿資訊
    leveraged_mode = bool(last_row.get('leveraged_mode', False))
    current_leverage = float(last_row.get('current_leverage', 1.0))
    positions_2x = int(last_row.get('positions_2x', 0))
    
    result = {
        'found': True,
        'csv_file': os.path.basename(selected_csv),
        'last_date': last_row['date'],
        'dca_positions': int(last_row['dca_position_count']),
        'ai_positions': int(last_row['ai_position_count']),
        'total_positions': int(last_row['total_position_count']),
        'leveraged_mode': leveraged_mode,
        'current_leverage': current_leverage,
        'positions_2x': positions_2x,
        'peak_price': current_peak_price,
        'note': last_row.get('note', ''),
        'open_positions': open_positions
    }
    
    leverage_status = "🔥 ON (2x)" if leveraged_mode else "OFF (1x)"
    print(f"  最後日期: {result['last_date']}")
    print(f"  持倉狀態: 總{result['total_positions']}倉 (DCA{result['dca_positions']} + AI{result['ai_positions']})")
    print(f"  槓桿狀態: {leverage_status} | Peak: {current_peak_price:,.2f}")
    
    return result


# =============================================================================
# Step 0: 建立盤後專屬工作區
# =============================================================================
def create_daily_workspace(date_str: str) -> dict:
    ws_path = os.path.join(DAILY_RUNS_PATH, date_str)
    os.makedirs(ws_path, exist_ok=True)
    
    workspace = {
        'root': ws_path,
        'cache': os.path.join(ws_path, 'cache'),
        'reports': os.path.join(ws_path, 'reports'),
    }
    for p in workspace.values():
        os.makedirs(p, exist_ok=True)
    
    print(f"[Workspace] 建立工作區: {ws_path}")
    return workspace


# =============================================================================
# Step 1: 讀取 Fixed LSTM 資訊並載入模型
# =============================================================================
def load_lstm_info_from_backtest(csv_file: str = None) -> dict:
    """
    從回測結果目錄讀取 lstm_info_*.json
    """
    pattern = os.path.join(BACKTEST_RESULTS_PATH, 'lstm_info_*.json')
    json_files = glob.glob(pattern)
    
    if not json_files:
        print(f"[Error] 找不到 LSTM 資訊: {pattern}")
        print(f"        請先執行: python backtest_v5_dca_hybrid_no_filter_fixed_lstm.py --start 2025-01-02")
        return None
    
    # 如果有指定 CSV，根據 CSV 起始日期尋找對應的 lstm_info
    target_json = None
    if csv_file:
        date_match = re.search(r'strat2_(\d{8})_', csv_file)
        if date_match:
            start_date_str = date_match.group(1)
            start_dt = datetime.strptime(start_date_str, '%Y%m%d')
            train_end_dt = start_dt - timedelta(days=1)
            train_end_str = train_end_dt.strftime('%Y%m%d')
            
            expected_json = os.path.join(BACKTEST_RESULTS_PATH, f'lstm_info_{train_end_str}.json')
            if os.path.exists(expected_json):
                target_json = expected_json
                print(f"[LSTM Info] 根據 CSV 起始日 ({start_date_str}) 選擇對應模型")
            else:
                print(f"[Warning] 找不到對應的 lstm_info_{train_end_str}.json")
    
    if target_json is None:
        target_json = sorted(json_files)[-1]
    
    print(f"[LSTM Info] 讀取: {os.path.basename(target_json)}")
    
    with open(target_json, 'r', encoding='utf-8') as f:
        lstm_info = json.load(f)
    
    print(f"  訓練截止日: {lstm_info.get('train_end_date', 'N/A')}")
    
    for model_key, info in lstm_info.get('models', {}).items():
        print(f"  {model_key}: {info.get('basename', 'N/A')}")
    
    return lstm_info


def load_fixed_lstm_models(lstm_info: dict) -> bool:
    """
    載入 Fixed LSTM 模型到 core_system
    """
    try:
        from twii_model_registry_5d import SelfAttention
    except ImportError:
        print("[Error] 無法載入 SelfAttention 類別")
        return False
    
    print("\n[Model Injection] 載入 Fixed LSTM 模型...")
    
    models = lstm_info.get('models', {})
    loaded_models = {}
    
    for model_key in ['model_1d', 'model_5d', 'model_20d']:
        if model_key not in models:
            print(f"[Error] 缺少 {model_key}")
            return False
        
        model_path = models[model_key]['path']
        
        if not os.path.exists(model_path):
            print(f"[Error] 找不到模型: {model_path}")
            return False
        
        model = keras.models.load_model(model_path, custom_objects={'SelfAttention': SelfAttention})
        
        scaler_feat_path = model_path.replace('model_', 'feature_scaler_').replace('.keras', '.pkl')
        scaler_tgt_path = model_path.replace('model_', 'target_scaler_').replace('.keras', '.pkl')
        meta_path = model_path.replace('model_', 'meta_').replace('.keras', '.json')
        
        scaler_feat = None
        scaler_tgt = None
        meta = {}
        
        if os.path.exists(scaler_feat_path):
            with open(scaler_feat_path, 'rb') as f:
                scaler_feat = pickle.load(f)
        if os.path.exists(scaler_tgt_path):
            with open(scaler_tgt_path, 'rb') as f:
                scaler_tgt = pickle.load(f)
        if os.path.exists(meta_path):
            with open(meta_path, 'r', encoding='utf-8') as f:
                meta = json.load(f)
        
        suffix = model_key.split('_')[1]
        loaded_models[f'model_{suffix}'] = model
        loaded_models[f'scaler_feat_{suffix}'] = scaler_feat
        loaded_models[f'scaler_tgt_{suffix}'] = scaler_tgt if scaler_tgt else scaler_feat
        loaded_models[f'meta_{suffix}'] = meta
        
        print(f"  ✅ {model_key}: {os.path.basename(model_path)}")
    
    loaded_models['loaded'] = True
    
    if not hasattr(core_system, '_LSTM_MODELS'):
        core_system._LSTM_MODELS = {}
    core_system._LSTM_MODELS.update(loaded_models)
    
    print("  ✅ 注入完成 (T+1, T+5, T+20)")
    return True


# =============================================================================
# Step 2: 特徵工程 (使用盤後完整資料)
# =============================================================================
def feature_engineering_with_fixed_lstm(workspace: dict, end_date: str) -> tuple:
    """
    特徵工程 (使用盤後完整資料 + Fixed LSTM)
    
    Returns:
        (df, actual_last_date): 特徵 DataFrame 和實際最後日期
    """
    print("\n" + "=" * 60)
    print("🔧 Step 2: 特徵工程 (使用盤後完整資料 + Fixed LSTM)")
    print("=" * 60)
    
    # 使用本地 CSV 載入完整盤後資料
    print(f"[Data] 載入本地資料 (2020-01-01 ~ {end_date})...")
    raw_df = core_system._load_local_twii_data(start_date="2020-01-01")
    
    # 篩選日期範圍
    end_dt_ts = pd.Timestamp(end_date)
    raw_df = raw_df[raw_df.index <= end_dt_ts]
    
    actual_last_date = raw_df.index[-1].strftime('%Y-%m-%d')
    print(f"[Data] 實際資料最後日期: {actual_last_date}")
    print(f"[Data] 資料筆數: {len(raw_df)}")
    
    # 匯出原始數據 CSV
    raw_csv_path = os.path.join(workspace['cache'], 'raw_data.csv')
    raw_df.to_csv(raw_csv_path)
    print(f"[Export] 原始數據已存檔: {raw_csv_path}")
    
    # 計算特徵
    print(f"[Compute] 計算特徵中 (使用 Fixed LSTM + 30次 MC Dropout)...")
    df = core_system.calculate_features(raw_df, raw_df, ticker="^TWII", use_cache=False)
    
    # 匯出特徵數據 CSV
    features_csv_path = os.path.join(workspace['cache'], 'processed_features.csv')
    df.to_csv(features_csv_path)
    print(f"[Export] 特徵數據已存檔: {features_csv_path}")
    
    return df, actual_last_date


# =============================================================================
# Step 3: V5 策略推論 (無濾網限制)
# =============================================================================
def v5_inference(workspace: dict, df: pd.DataFrame, open_positions: list = None, close_price: float = None) -> dict:
    """
    V5 策略推論
    
    Args:
        workspace: 工作區資訊
        df: 特徵 DataFrame
        open_positions: 從回測讀取的 AI 持倉清單 (含 buy_price, buy_date)
        close_price: 今日收盤價 (用於計算各持倉報酬率)
    """
    print("\n" + "=" * 60)
    print("🎯 Step 3: V5 策略推論 (無濾網限制)")
    print("=" * 60)
    
    from stable_baselines3 import PPO
    latest = df.iloc[-1]
    
    # 如果沒傳入 close_price，從 df 取得
    if close_price is None:
        close_price = float(latest['Close'])
    
    # 保留 filter 資訊供參考，但不影響買入決策
    signal_buy_filter = bool(latest.get('Signal_Buy_Filter', False))
    print(f"  [濾網] Signal_Buy_Filter = {signal_buy_filter} (僅供參考，V5不受限)")
    
    features = np.array([latest.get(col, 0.0) for col in core_system.FEATURE_COLS], dtype=np.float32).reshape(1, -1)
    features = np.nan_to_num(features, nan=0.0, posinf=1.0, neginf=-1.0)
    
    # 載入 V5 模型
    buy_path = os.path.join(V5_MODEL_PATH, 'ppo_buy_twii_final.zip')
    sell_path = os.path.join(V5_MODEL_PATH, 'ppo_sell_twii_final.zip')
    
    if not os.path.exists(buy_path):
        return {'error': 'V5 Model not found', 'filter_signal': signal_buy_filter}

    try:
        buy_agent = PPO.load(buy_path)
        sell_agent = PPO.load(sell_path)
        
        # ===== Buy Agent =====
        b_act, _ = buy_agent.predict(features, deterministic=True)
        b_obs = buy_agent.policy.obs_to_tensor(features)[0]
        b_prob = buy_agent.policy.get_distribution(b_obs).distribution.probs.detach().cpu().numpy()[0]
        
        ai_action = 'BUY' if b_act[0] == 1 else 'WAIT'
        buy_prob = float(b_prob[1]) if b_act[0] == 1 else float(b_prob[0])
        
        # V5: 無濾網限制，直接使用 AI 決策
        buy_signal = ai_action
        filter_note = "✅通過" if signal_buy_filter else "❌未通過"
        print(f"  [V5] Buy: {buy_signal} ({buy_prob:.1%}) | 濾網: {filter_note}")
        
        # ===== Sell Agent (真實持倉分析) =====
        position_decisions = []
        
        if open_positions and len(open_positions) > 0:
            print(f"  [V5] 分析 {len(open_positions)} 筆 AI 持倉...")
            
            for pos in open_positions:
                buy_price = float(pos.get('buy_price', 0))
                buy_date = pos.get('buy_date', 'N/A')
                
                if buy_price > 0:
                    # 計算真實報酬率
                    current_return = close_price / buy_price
                    return_pct = (current_return - 1) * 100
                    
                    # 構建 Sell Agent 的觀察值 (特徵 + 報酬率)
                    s_feat = np.concatenate([features[0], [current_return]]).reshape(1, -1).astype(np.float32)
                    s_act, _ = sell_agent.predict(s_feat, deterministic=True)
                    
                    # 取得機率分布以計算信心
                    s_obs = sell_agent.policy.obs_to_tensor(s_feat)[0]
                    s_prob = sell_agent.policy.get_distribution(s_obs).distribution.probs.detach().cpu().numpy()[0]
                    
                    sell_action = 'SELL' if s_act[0] == 1 else 'HOLD'
                    sell_conf = float(s_prob[1]) if s_act[0] == 1 else float(s_prob[0])
                    
                    # 判斷是否觸發停損 (硬性規則: -8%)
                    triggered_stop_loss = current_return < 0.92
                    
                    position_decisions.append({
                        'buy_date': buy_date,
                        'buy_price': buy_price,
                        'current_return': current_return,
                        'return_pct': return_pct,
                        'action': sell_action,
                        'confidence': sell_conf,
                        'triggered_stop_loss': triggered_stop_loss,
                        'final_action': 'SELL' if triggered_stop_loss else sell_action
                    })
        else:
            print(f"  [V5] 無 AI 持倉，跳過 Sell Agent 分析")
        
        return {
            'filter_signal': signal_buy_filter,
            'buy_decision': buy_signal,
            'buy_confidence': buy_prob * 100,
            'buy_action': int(b_act[0]),
            'ai_action': ai_action,
            'position_decisions': position_decisions  # 新增：每筆持倉的 Sell Agent 判斷
        }
    except Exception as e:
        print(f"  [Error] V5 Inference: {e}")
        return {'error': str(e), 'filter_signal': signal_buy_filter}


# =============================================================================
# Step 4: 輸出報告
# =============================================================================
def generate_report(workspace: dict, df: pd.DataFrame, res: dict, date_str: str, 
                    backtest_status: dict = None):
    print("\n" + "=" * 60)
    print("📊 Step 4: 盤後分析報告 (V5 Fixed LSTM)")
    print("=" * 60)
    
    last = df.iloc[-1]
    filter_status = res.get('filter_signal', False)
    close_price = float(last['Close'])
    volume = float(last.get('Volume', 0))
    
    lines = []
    lines.append("=" * 50)
    lines.append(f"📅 V5 盤後分析報告 - {date_str}")
    lines.append(f"⏰ 更新時間: {datetime.now().strftime('%H:%M:%S')}")
    lines.append("=" * 50)
    lines.append(f"📊 Open:  {last['Open']:,.2f}")
    lines.append(f"📈 High:  {last['High']:,.2f}")
    lines.append(f"📉 Low:   {last['Low']:,.2f}")
    lines.append(f"💰 Close: {close_price:,.2f} (收盤)")
    lines.append(f"📦 Volume: {volume:.2f} 億元")
    lines.append("-" * 50)
    
    # 濾網狀態 (僅供參考)
    filter_icon = "✅" if filter_status else "🚫"
    lines.append(f"📋 [濾網狀態] {filter_icon} {'通過' if filter_status else '未通過'} (V5不受此限制)")
    lines.append("-" * 50)
    
    # 槓桿狀態 (Strategy 1 Only)
    if backtest_status and 'leveraged_mode' in backtest_status:
        lev_mode = backtest_status['leveraged_mode']
        peak_price = backtest_status.get('peak_price', 0)
        
        lev_icon = "🔥" if lev_mode else "❄️"
        lev_str = "ON (2倍槓桿)" if lev_mode else "OFF (1倍槓桿)"
        
        lines.append(f"⚡ [2x 槓桿監控] (Strategy 1)")
        lines.append(f"   狀態: {lev_icon} {lev_str}")
        
        if peak_price > 0:
            dd_pct = (close_price - peak_price) / peak_price
            lines.append(f"   高點: {peak_price:,.2f} | 目前跌幅: {dd_pct*100:.2f}%")
            if not lev_mode:
                trigger_price = peak_price * 0.92  # 8% threshold
                dist_to_trigger = (close_price - trigger_price) / close_price
                lines.append(f"   觸發: {trigger_price:,.2f} (距離: {dist_to_trigger*100:.2f}%)")
            else:
                lines.append(f"   退出: {peak_price:,.2f} (回到高點即退出)")
        lines.append("-" * 50)

    # LSTM
    lines.append("🔮 [分析師 LSTM] (Fixed 模型)")
    pred_1d_pct = last.get('LSTM_Pred_1d', 0)
    price_1d = close_price * (1 + pred_1d_pct)
    
    pred_5d_pct = last.get('LSTM_Pred_5d', 0)
    price_5d = close_price * (1 + pred_5d_pct)
    
    pred_20d_pct = last.get('LSTM_Pred_20d', 0)
    price_20d = close_price * (1 + pred_20d_pct)

    lines.append(f"   T+1 預測: {pred_1d_pct*100:+.2f}% (目標價: {price_1d:,.2f}) | 信心度: {last.get('LSTM_Conf_1d', 0)*100:.1f}%")
    lines.append(f"   T+5 預測: {pred_5d_pct*100:+.2f}% (目標價: {price_5d:,.2f}) | 信心度: {last.get('LSTM_Conf_5d', 0)*100:.1f}%")
    lines.append(f"   T+20 預測: {pred_20d_pct*100:+.2f}% (目標價: {price_20d:,.2f}) | 信心度: {last.get('LSTM_Conf_20d', 0)*100:.1f}%")
    lines.append("-" * 50)

    # V5 顯性特徵
    lines.append("📐 [關鍵特徵]")
    lines.append(f"   MA20 動能: {last.get('Feat_MA20_Slope', 0)*100:+.2f}%  (>0 轉強)")
    lines.append(f"   市場體制: {last.get('Feat_Trend_Gap', 0)*100:+.2f}%  (>0 多頭結構)")
    lines.append(f"   短線乖離: {last.get('Feat_Bias_MA20', 0)*100:+.2f}%")
    lines.append(f"   季線距離: {last.get('Feat_Dist_MA60', 0)*100:+.2f}%")
    lines.append(f"   年線位置: {last.get('Feat_Dist_MA240', 0)*100:+.2f}%  (>0 長多)")
    lines.append(f"   相對量能: {last.get('Feat_Vol_Ratio', 0):.2f}x   (>1.0 放量)")
    lines.append("-" * 50)
    
    # V5 RL
    lines.append("🤖 [操盤手 V5] (對稱獎勵 + 無濾網)")
    if 'error' in res:
        lines.append(f"   ❌ 錯誤: {res['error']}")
    else:
        buy_signal = res.get('buy_decision', 'N/A')
        buy_prob = res.get('buy_confidence', 0) / 100
        ai_action = res.get('ai_action', 'WAIT')
        buy_icon = "🚀" if ai_action == 'BUY' else "💤" if ai_action == 'WAIT' else "🚫"
        
        lines.append(f"   🛒 買入訊號: {buy_icon} {buy_signal} ({buy_prob:.1%})")

    lines.append("-" * 50)
    
    # Advice (V5: 無濾網限制)
    ai_action = res.get('ai_action', 'N/A')
    if ai_action == 'BUY':
        advice = "⭐⭐ V5 強力買進 (Strong Buy) ⭐⭐"
    elif ai_action == 'WAIT':
        advice = "💤 空手觀望 (Wait)"
    else:
        advice = "❓ 訊號不明"
    
    # 額外標注濾網狀態供參考
    filter_note = "濾網✅" if filter_status else "濾網❌"
    advice += f" [{filter_note}]"
        
    lines.append(f"💡 盤後建議: {advice}")
    lines.append("-" * 50)
    
    # 回測持倉狀態
    if backtest_status and backtest_status.get('found'):
        csv_file = backtest_status.get('csv_file', 'N/A')
        date_match = re.search(r'(\d{8})_(\d{8})\.csv$', csv_file)
        if date_match:
            start_date = f"{date_match.group(1)[:4]}-{date_match.group(1)[4:6]}-{date_match.group(1)[6:8]}"
            end_date = f"{date_match.group(2)[:4]}-{date_match.group(2)[4:6]}-{date_match.group(2)[6:8]}"
            date_range_str = f"{start_date} ~ {end_date}"
        else:
            date_range_str = csv_file
        
        lines.append(f"💼 [回測持倉狀態] 檔案: {csv_file}")
        lines.append(f"   📅 回測期間: {date_range_str}")
        lines.append(f"   🏛️  DCA 倉位: {backtest_status['dca_positions']} 倉")
        lines.append(f"   🤖 AI 倉位: {backtest_status['ai_positions']} 倉")
        lines.append(f"   📊 總倉數: {backtest_status['total_positions']} 倉")
        lines.append(f"   📝 最後操作: {backtest_status.get('note', 'N/A')}")
        
        # 預測今日操作
        lines.append("-" * 50)
        lines.append("🔮 [今日預測] (基於收盤價)")
        
        ai_positions = backtest_status['ai_positions']
        dca_positions = backtest_status['dca_positions']
        
        # 預測買入 (V5: 無濾網限制，純看 AI 決策)
        predicted_buy = 0
        if ai_action == 'BUY':
            lines.append(f"   🟢 買入預測: AI+1倉 (V5 無濾網限制, AI建議BUY)")
            predicted_buy = 1
        else:
            lines.append(f"   ⚪ 買入預測: 無 (AI:{ai_action})")
        
        # 預測賣出 (使用 position_decisions)
        position_decisions = res.get('position_decisions', [])
        predicted_sell = 0
        
        if position_decisions:
            lines.append("-" * 50)
            lines.append("📦 [AI持倉明細 + Sell Agent 判斷]")
            
            for i, pd in enumerate(position_decisions, 1):
                buy_date = pd.get('buy_date', 'N/A')
                buy_price = pd.get('buy_price', 0)
                return_pct = pd.get('return_pct', 0)
                action = pd.get('action', 'HOLD')
                confidence = pd.get('confidence', 0)
                final_action = pd.get('final_action', 'HOLD')
                triggered_stop_loss = pd.get('triggered_stop_loss', False)
                
                # 決定顯示格式
                if triggered_stop_loss:
                    status_icon = "🔴 SELL"
                    reason = f"停損觸發 (AI: {action} {confidence:.1%})"
                elif final_action == 'SELL':
                    status_icon = "🔴 SELL"
                    reason = f"AI決定 ({confidence:.1%})"
                else:
                    status_icon = "🟢 HOLD"
                    reason = f"AI決定 ({confidence:.1%})"
                
                lines.append(f"   #{i} 買入: {buy_date} @ {buy_price:,.2f}")
                lines.append(f"       報酬: {return_pct:+.2f}% | {status_icon} {reason}")
                
                if final_action == 'SELL':
                    predicted_sell += 1
        elif ai_positions > 0:
            lines.append(f"   ⚠️ 無持倉明細資料")
        else:
            lines.append(f"   ⚪ 賣出預測: 無 (AI 無持倉)")
        
        # 計算預估總倉
        predicted_ai = ai_positions + predicted_buy - predicted_sell
        predicted_total = dca_positions + predicted_ai
        
        lines.append("-" * 50)
        lines.append("📊 [預估明日倉位]")
        lines.append(f"   DCA: {dca_positions} 倉 (不變)")
        change = predicted_buy - predicted_sell
        change_str = f"+{change}" if change > 0 else str(change) if change < 0 else "±0"
        lines.append(f"   AI:  {ai_positions} → {predicted_ai} 倉 ({change_str})")
        lines.append(f"   總計: {backtest_status['total_positions']} → {predicted_total} 倉")
        
    else:
        lines.append("💼 [回測持倉狀態] 未找到回測結果")
        lines.append("   請先執行: python backtest_v5_dca_hybrid_no_filter_fixed_lstm.py --start 2025-01-02")
    
    lines.append("=" * 50)
    
    report = "\n".join(lines)
    print(report)
    
    # Save
    with open(os.path.join(workspace['reports'], 'daily_summary.txt'), 'w', encoding='utf-8') as f:
        f.write(report)
    
    json_data = {
        'date': date_str,
        'filter_status': filter_status,
        'market': {'close': close_price, 'volume': volume},
        'lstm': {
            'pred_1d': float(pred_1d_pct), 'price_1d': float(price_1d),
            'pred_5d': float(pred_5d_pct), 'price_5d': float(price_5d),
            'pred_20d': float(pred_20d_pct), 'price_20d': float(price_20d),
        },
        'v5': res,
        'advice': advice
    }
    with open(os.path.join(workspace['reports'], 'daily_summary.json'), 'w', encoding='utf-8') as f:
        json.dump(json_data, f, indent=2, ensure_ascii=False)
    
    print(f"\n[Report] 已儲存至: {workspace['reports']}")


# =============================================================================
# Main
# =============================================================================
def main():
    import argparse
    
    parser = argparse.ArgumentParser(
        description='V5 盤後分析系統 (Fixed LSTM + No Filter)',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
使用範例:
  python daily_ops_v5_fixed_lstm.py                    # 使用最新回測結果
  python daily_ops_v5_fixed_lstm.py -i                 # 互動式選擇回測 CSV
  python daily_ops_v5_fixed_lstm.py --backtest-start 2025-01-02  # 指定回測起始日
        '''
    )
    parser.add_argument(
        '-i', '--interactive',
        action='store_true',
        help='互動式選擇回測 CSV 檔案 (使用方向鍵)'
    )
    parser.add_argument(
        '--backtest-start', 
        type=str, 
        default=None,
        help='回測起始日期 (YYYY-MM-DD 或 YYYYMMDD 格式)'
    )
    args = parser.parse_args()
    
    # 計算今天日期 (排除週末)
    today = datetime.now()
    if today.weekday() == 5:  # Saturday
        today -= timedelta(days=1)
    elif today.weekday() == 6:  # Sunday
        today -= timedelta(days=2)
    
    date_str = today.strftime('%Y-%m-%d')
    
    print("=" * 60)
    print(f"🚀 V5 盤後分析系統 (Fixed LSTM + No Filter) - {date_str}")
    print("=" * 60)
    
    # 檢查 V5 模型
    if not os.path.exists(os.path.join(V5_MODEL_PATH, 'ppo_buy_twii_final.zip')):
        print(f"\n[Error] V5 模型不存在: {V5_MODEL_PATH}")
        print("請先執行 train_v5_models.py 完成訓練")
        sys.exit(1)
    
    # Step 0: 建立工作區
    ws = create_daily_workspace(date_str)
    
    # Step 0.5: 讀取回測持倉狀態
    print("\n[Backtest] 讀取回測持倉狀態...")
    backtest_status = load_latest_backtest_status(args.backtest_start, interactive=args.interactive)
    
    # Step 1: 讀取 Fixed LSTM 資訊
    print("\n" + "=" * 60)
    print("📚 Step 1: 載入 Fixed LSTM 模型 (不重訓)")
    print("=" * 60)
    
    lstm_info = load_lstm_info_from_backtest(backtest_status.get('csv_file'))
    if not lstm_info:
        print("[Error] 無法載入 LSTM 資訊")
        sys.exit(1)
    
    if not load_fixed_lstm_models(lstm_info):
        print("[Error] 無法載入 Fixed LSTM 模型")
        sys.exit(1)
    
    # Step 2: 特徵工程 (使用盤後完整資料)
    df, actual_date = feature_engineering_with_fixed_lstm(ws, date_str)
    
    if actual_date != date_str:
        print(f"[Warning] 預估日期 {date_str} 與實際資料日期 {actual_date} 不同")
        print(f"[Info] 報告將使用實際資料日期: {actual_date}")
    
    # Step 3: V5 策略推論 (傳入真實持倉資訊)
    open_positions = backtest_status.get('open_positions', []) if backtest_status else []
    close_price = float(df.iloc[-1]['Close'])
    res = v5_inference(ws, df, open_positions=open_positions, close_price=close_price)
    
    # Step 4: 輸出報告
    generate_report(ws, df, res, actual_date, backtest_status)
    
    print("\n" + "=" * 60)
    print("✅ V5 盤後分析完成 (Fixed LSTM + No Filter)！")
    print("=" * 60)


if __name__ == "__main__":
    main()
